### ISSUE TITLE
Install this theme and plugin

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#1]
bbottoms.editllc.com

Install this theme: https://slocumthemes.com/wordpress-themes/modern-estate-free/

Install this plugin: http://github.com/sdsweb/Easy-Real-Estate-Plugin

You might need to watch the video on the 1st link above on how to build the site and use the theme. 

due:
10-13-15 1p

**Comment by jperez4509** [comment]
Done. I have installed the theme and the plugin as well as another required plugin that is used to show the property images. I do think this theme can work for this client.
