### ISSUE TITLE
new test site that replicates old site bbottoms-old.editllc.com

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#10]
shared the creds via lastpass

please go in and double-check the admin interface, then review and replicate any functionality to our new site we're creating for him. 

one page specifically is: http://buyorsellfresno.com/mls/  where he uses an iframe in the wysiwyg. 

due:
11-25-15   12p

**Comment by vanderbeam** [comment]
@rodneystrong There's an open house tab on the old site. The plugin I currently have for the listings doesn't generate a map automatically, but it does give you an option when creating the listing to enter a date for the open house which will create a red bar at the bottom listing the date (see screenshot below). OR, I can find another plugin that includes excerpts (from previous issue) AND an integrated map. The Open house "map" on the previous site is just that same MLS iframe.

![ss](https://cloud.githubusercontent.com/assets/12962001/11384165/646ef186-92c2-11e5-905d-11769af3decb.png)

**Comment by vanderbeam** [comment]
@rodneystrong Did you buy the new theme?

**Comment by rodneystrong** [comment]
So so sorry Meg. I FINALLY purchased and downloaded the theme. It's uploaded to the google drive now.
