### ISSUE TITLE
Fix content in footer

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#13]
- Lorem ipsum in the footer under "About Real homes". Please refer to his current live site for guidance on what to put there

- His "Contact Info" section is incorrect  (also, the email address should be buyorsellfresno@outlook.com)

due:
12-18-15    5p

**Comment by rodneystrong** [comment]
Following up on this. Please respond by 12-19-15 3p with an updated due date you can reach.

**Comment by vanderbeam** [comment]
This is done except I do have one question.... under "Contact Buy or Sell Fresno" it lists the numbers as:
o (559) 201-8000
f (559) 549-6210

Then lists a different number below under "Contact Brandon" ((559) 930-6226). I assume this may be his direct cell number. Should I list it as such?

**Comment by rodneystrong** [comment]
Good intuition. And yes definitely. But you're on vacation, so enjoy yourself. 

I already made that change.
