### ISSUE TITLE
Build out the top header

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#5]
Use the same logo/text as his live site and put in all the same menu items as well. 

Link up the ones that we have content for (like the mortgage calculator, listings, etc).

due:
10-17-15  10p

**Comment by rodneystrong** [comment]
man oh man. you fail me yet again joel. 

:' (

**Comment by jperez4509** [comment]
I know I know. This has been completed. However, I don't know how to get the Fresno MLS search form he has on his current site. I looked at it using inspect element and I see its an iframe. Can you help me with that?

**Comment by rodneystrong** [comment]
;D 
I'm glad you brought up MLS. @EditLLC/marketing said he won't be utilitzing MLS on his new site, but I'll confirm that again with him. 

In the event that he does, I have an option I can look-up to help with that.
