### ISSUE TITLE
Listing page photo grid

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#8]
Currently when you click on "Photos" when viewing a listing (like this one: http://bbottoms.editllc.com/listings/2134-n-wilson-ave-fresno-ca-93704/) the photos don't line up in a grid, they just stack on top of each other. Can you make it so they get into a grid? 

Also, can you make it so when you click on a photo, it instead pops up in a modal window, instead of a new tab?

<img width="730" alt="screen shot 2015-11-11 at 1 59 09 pm" src="https://cloud.githubusercontent.com/assets/539962/11104288/9c375022-887c-11e5-8e94-996ea62287e2.png">

due:
11-11-15  11p

**Comment by rodneystrong** [comment]
Meg?

**Comment by vanderbeam** [comment]
Oh shoot, sorry I never commented that I got this done Alex. After I made the photos a grid I got distracted by looking into hotbox plugins and stuff to make the photos pop up.

**Comment by rodneystrong** [comment]
good job with this!
