### ISSUE TITLE
A bit of a redesign

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/bbottoms-realestate#9]
Maybe try and go for this look: 

http://realhomes.inspirythemes.biz/

What I like most about that theme is how their different sections on the home page dont have a large space separating them but they are still noticeably different sections. Also, all sans serif fonts. 

The way it shows each listing in a rectangular shape with snippets of the necessary details is great. 

I think I'll give a video explanation with some more detail later tonight to give a better idea of what im saying. 

due:
11-21-15    4p

updated due:
12-12-15   5p

updated due:
12-28-15   530p

**Comment by vanderbeam** [comment]
@rodneystrong Adding excerpts is not a feature this listing plugin has. Do you want me to install a different one that has excerpts in the listings?

**Comment by rodneystrong** [comment]
I'm not sure if this is still relevant after we've gotten the new theme, but yes, do what you need to get all the functionality he already has.

**Comment by rodneystrong** [comment]
Updated the due date to 12-12-15   5p  for the site to be complete

**Comment by rodneystrong** [comment]
How's the site coming along? Any fears about meeting the 12-12 Saturday deadline?

What are some potential hang-ups that I can help with?

**Comment by vanderbeam** [comment]
I may need an extra day or two on this. There are some issues I'm having that I haven't been able to figure out yet.

**Comment by rodneystrong** [comment]
Ok, thanks for the update. For posterity's sake, please notate the issues you're having here before you make your next update.

**Comment by vanderbeam** [comment]
My biggest issues are not being able to figure out how to edit the front page and not being able to figure out how to add the maps to the banners or the home page.

**Comment by vanderbeam** [comment]
@rodneystrong 
- Needs better resolution photos for site and some better angles (see home page slider for an example)
- Need to begin listing descriptions/excerps for property details
- Need to begin noting more features (suggestions: how many floors, garage (and how many cars it holds), pool, fireplace, ceiling fans, basement/attic)
- Avoid filtering the photos like http://bbottoms.editllc.com/property/10851-e-swift... and http://bbottoms.editllc.com/property/5466-w-griffi... . (it's just my personal opinion they don't match the site and look a little tacky... this is suppose to be a professional real estate site, not instagram) 
- does he want to start charging for "Featured" listings that will appear on the front page and/or slider? Does he already do this? I just chose houses I felt made a good to modest impression.

To make the MLS work we have to do the following:
"First you have to register a trial account at www.diversesolutions.com and get an activation key.
After that you have to install dsIDXpress (http://wordpress.org/plugins/dsidxpress/) and activate it using activation key you got from registering with divers solutions website. Related screen shot is given below."

**Comment by vanderbeam** [comment]
What is left:
- So after studying the original template some I realized I can't get the Google imaged there like I thought I could, so I'll have to use a still shot of each individual house for each listing, which wouldn't be a big deal if I didn't know most of the pictures look very poor blown up to 2000x700. I coud also always force out the banner by trying a `display:none` or something in the css for that module.
- I found the edocumentatoon for the revolutionary slider and so hopefully I'll be able to actually figure out how to use the thing which ay even solve our my above statementl 
- The MLS link I posted in my previous comments need to be singed up for so we can start integrating their MLS into the site'
We also may just have to accept that an "Open House" nav item is unnecessary and that open houses can be listed on the propertis themselves. 

After this still is done I can sweep through, tie up loose ends, and we'll be ready.

**Comment by rodneystrong** [comment]
Good question on charging for "featured" listings; i'll pass it along. For now, what you did is good. 

Go ahead and just use the low-res images for the 2000x700 picture spots. The goal is to give Brandon the idea of what the site will look like with all his content. He'll be smart enough to recognize that pixelated images aren't the best. 

If I remember correctly, his MLS is just a copy/paste of the iframe code right? Have you tried that yet?

**Comment by vanderbeam** [comment]
This still leave a couple of my questions unanswered.
- Do you want me to make photos banners in each of the listings or just css out the banner area? I only ask because for the banners you have to manually crop each picture for each banner. I'm not saying I mind doing that, but I don't know how thrilled he will have to be able doing it every time he uploads a new listing. 
- I was under the impression that the idea of getting this theme was because the MLS plugin integrates the theme's Google map system (in addition to looking much better than the iframe). Integrating this MLS plugin that already has functionality with this theme will also be more friendly towards integrating property listing on the site. Link to the theme's MLS preview: http://themeforest.net/item/real-homes-wordpress-real-estate-theme/full_screen_preview/5373914. Didn't you also mention that the person wasn't maintaining the MLS site he was using and he was thinking of switching providers anyway? 
- Is removing "Open Houses" an option since the dates will be visible on the listings themselves?

Last minute thought:
- He should also consider taking advantage of adding video of the homes (they also offer floor plan uploads)

**Comment by rodneystrong** [comment]
In my previous comment I mentioned the "2000x700 picture spots"; I was actually talking about those photo banners in each listing. So yes, just use a low res image for those sections; I trust you to choose a pic that'll look good there for each different listing. 

No, the purpose of this theme was because of the way it looked and how it created well-formatted post types for the property listings for us. He was always going to use his own personal listings and maybe the free MLS embed code he currently has. The ability to use IDXPress was just a possible bonus we were going to present to him. My bad if that wasn't clear before. 
Also, if you look at his current live site, his MLS page has "expired".

Let's table the "open house" discussion for later. Please make that one of your tasks to remind me of next week. 

He's asked about a video option before, i think it's just a matter of having a video now.

**Comment by rodneystrong** [comment]
Please comment here with a due date/time when you think this could all be done.

**Comment by rodneystrong** [comment]
Sorry @vanderbeam but I need this done sooner than later. Reassigning to @rampage1213 

Quintin, please read through this whole issue and come talk to me by 5:30p so I can make sure you're clear about what's needed. Meg did a good job setting up the site and importing all the content. You just now need to get familiar with the different configuration options, where things are, and how the different post types work. 

Here is the theme documentation: http://realhomes.inspirythemes.biz/doc/

due:
12-28-15  530p

**Comment by rampage1213** [comment]
Ok I get what needs to be done 
![screen shot 2015-12-28 at 6](https://cloud.githubusercontent.com/assets/7650448/12028752/5f55b93e-ad91-11e5-9f05-b7672ec9b2ee.png)
Just add the best photo we have right where it says 2000x266

**Comment by rampage1213** [comment]
I will need to push the deadline to 12-28-15 12am

**Comment by rampage1213** [comment]
@rodneystrong I dont have the creds for this site

**Comment by rampage1213** [comment]
Done!
